### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Zeus-Iqd** [lfyfly/vue-scrollbar-custom#1]
说找不到模块。

**Comment by Zeus-Iqd** [comment]
Unhandled rejection Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at E:\IBS\node_modules\consolidate\lib\consolidate.js:825:33
    at E:\IBS\node_modules\consolidate\lib\consolidate.js:144:5
    at promisify (E:\IBS\node_modules\consolidate\lib\consolidate.js:137:10)
    at Function.exports.pug.render (E:\IBS\node_modules\consolidate\lib\consolidate.js:821:10)
    at Object.module.exports (E:\IBS\node_modules\vue-loader\lib\template-compiler\preprocessor.js:30:20)
    at LOADER_EXECUTION (E:\IBS\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (E:\IBS\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (E:\IBS\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at iterateNormalLoaders (E:\IBS\node_modules\loader-runner\lib\LoaderRunner.js:218:10)

**Comment by Zeus-Iqd** [comment]
????

**Comment by maplehsu** [comment]
同问。。。 这个插件是不是用不了。。

**Comment by felix9ia** [comment]
同问！感觉这个插件很棒！坚持，作者！

**Comment by sherry1510** [comment]
同问，你们都解决了吗

**Comment by maplehsu** [comment]
然而作者没了

**Comment by JoeyHe912** [comment]
还需要安装四个模块
npm install pug node-sass sass-loader babel-preset-es2015 --save-dev

**Comment by felix9ia** [comment]
刚看到！好的，感谢您的帮助！




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            贾鹏飞
                            
                            
                                
                                    邮箱：felixjiawork@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年03月26日 10:15，JoeyHe912 写道： 还需要安装四个模块
npm install pug node-sass sass-loader babel-preset-es2015 --save-dev

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lfyfly/vue-scrollbar-custom","title":"lfyfly/vue-scrollbar-custom","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lfyfly/vue-scrollbar-custom"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JoeyHe912 in #1: 还需要安装四个模块\r\nnpm install pug node-sass sass-loader babel-preset-es2015 --save-dev"}],"action":{"name":"View Issue","url":"https://github.com/lfyfly/vue-scrollbar-custom/issues/1#issuecomment-376027370"}}}

**Comment by Hxmic** [comment]
这个兼容性怎么样
